byTorsten:
  React:
    LinuxRenderer:
      path: 'resource://byTorsten.React.LinuxRenderer/Private/bin/react-renderer-linux'
      keepAlive: true
      tempPath: '%FLOW_PATH_DATA%React'
      processTimeout: 2.0
      socketTimeout: 30.0
